### ISSUE TITLE
Missing 'pry' dependancy

### ISSUE THREAD

**Issue by ikbenben** [richardbrodie/fitreader#1]
I'm trying to install fitreader into our rails application and getting the following error when trying to run the application
```
/usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- pry (LoadError)
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/bundle/gems/fitreader-0.3.2/lib/fitreader/fit.rb:10:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/bundle/gems/fitreader-0.3.2/lib/fitreader.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /fitmo/config/application.rb:4:in `<top (required)>'
	from /usr/local/bundle/gems/railties-3.2.22/lib/rails/commands.rb:39:in `require'
	from /usr/local/bundle/gems/railties-3.2.22/lib/rails/commands.rb:39:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

There seems to be a dependancy on 'pry' which is missing from the gemspec

**Comment by richardbrodie** [comment]
Good catch! Should be fixed now, sorry about that.
